-- SCRIPT TO LIST CITIES OF CALIFORNIA WITHOUT USING JOIN

-- SELECT CITIES OF CALIFORNIA USING SUBQUERY
SELECT * FROM cities
WHERE state_id = (
	SELECT id FROM states WHERE name 'California'
)
ORDER BY id ASC;
